file = "C:/Users/WXH/Desktop/template2.xlsx"
[excel]
    rowbegin = 2
    colbegin = "a"
    email = "a"
    name = "c"
    sheet = "工资 "
[mail]
    password = "Wang0000"
    account = "wangxiaohua@91ruler.com"
    server = "smtp.exmail.qq.com"
    port = 25
