file = "C:/Users/WXH/Desktop/工资条格式.xlsx"
[excel]
    rowbegin = 3
    colbegin = "a"
    colend = "p"
    email = "a"
    name = "c"
    sheet = "工资 "
[mail]
    password = "123456"
    account = "jiangjing@91ruler.com"
    server = "smtp.exmail.qq.com"
    port = 25
